# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eugene/Desktop/JobShop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eugene/Desktop/JobShop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eugene/Desktop/JobShop/CMakeFiles /home/eugene/Desktop/JobShop/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eugene/Desktop/JobShop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

configure.o: configure.cpp.o

.PHONY : configure.o

# target to build an object file
configure.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/configure.cpp.o
.PHONY : configure.cpp.o

configure.i: configure.cpp.i

.PHONY : configure.i

# target to preprocess a source file
configure.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/configure.cpp.i
.PHONY : configure.cpp.i

configure.s: configure.cpp.s

.PHONY : configure.s

# target to generate assembly for a file
configure.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/configure.cpp.s
.PHONY : configure.cpp.s

cuChromosome.o: cuChromosome.cpp.o

.PHONY : cuChromosome.o

# target to build an object file
cuChromosome.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuChromosome.cpp.o
.PHONY : cuChromosome.cpp.o

cuChromosome.i: cuChromosome.cpp.i

.PHONY : cuChromosome.i

# target to preprocess a source file
cuChromosome.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuChromosome.cpp.i
.PHONY : cuChromosome.cpp.i

cuChromosome.s: cuChromosome.cpp.s

.PHONY : cuChromosome.s

# target to generate assembly for a file
cuChromosome.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuChromosome.cpp.s
.PHONY : cuChromosome.cpp.s

cuJob.o: cuJob.cpp.o

.PHONY : cuJob.o

# target to build an object file
cuJob.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuJob.cpp.o
.PHONY : cuJob.cpp.o

cuJob.i: cuJob.cpp.i

.PHONY : cuJob.i

# target to preprocess a source file
cuJob.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuJob.cpp.i
.PHONY : cuJob.cpp.i

cuJob.s: cuJob.cpp.s

.PHONY : cuJob.s

# target to generate assembly for a file
cuJob.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuJob.cpp.s
.PHONY : cuJob.cpp.s

cuMachine.o: cuMachine.cpp.o

.PHONY : cuMachine.o

# target to build an object file
cuMachine.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuMachine.cpp.o
.PHONY : cuMachine.cpp.o

cuMachine.i: cuMachine.cpp.i

.PHONY : cuMachine.i

# target to preprocess a source file
cuMachine.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuMachine.cpp.i
.PHONY : cuMachine.cpp.i

cuMachine.s: cuMachine.cpp.s

.PHONY : cuMachine.s

# target to generate assembly for a file
cuMachine.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cuMachine.cpp.s
.PHONY : cuMachine.cpp.s

cumain.o: cumain.cu.o

.PHONY : cumain.o

# target to build an object file
cumain.cu.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cumain.cu.o
.PHONY : cumain.cu.o

cumain.i: cumain.cu.i

.PHONY : cumain.i

# target to preprocess a source file
cumain.cu.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cumain.cu.i
.PHONY : cumain.cu.i

cumain.s: cumain.cu.s

.PHONY : cumain.s

# target to generate assembly for a file
cumain.cu.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/cumain.cu.s
.PHONY : cumain.cu.s

job_base.o: job_base.cpp.o

.PHONY : job_base.o

# target to build an object file
job_base.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/job_base.cpp.o
.PHONY : job_base.cpp.o

job_base.i: job_base.cpp.i

.PHONY : job_base.i

# target to preprocess a source file
job_base.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/job_base.cpp.i
.PHONY : job_base.cpp.i

job_base.s: job_base.cpp.s

.PHONY : job_base.s

# target to generate assembly for a file
job_base.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/job_base.cpp.s
.PHONY : job_base.cpp.s

unit_test.o: unit_test.cpp.o

.PHONY : unit_test.o

# target to build an object file
unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/unit_test.cpp.o
.PHONY : unit_test.cpp.o

unit_test.i: unit_test.cpp.i

.PHONY : unit_test.i

# target to preprocess a source file
unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/unit_test.cpp.i
.PHONY : unit_test.cpp.i

unit_test.s: unit_test.cpp.s

.PHONY : unit_test.s

# target to generate assembly for a file
unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/unit_test.cpp.s
.PHONY : unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Main"
	@echo "... configure.o"
	@echo "... configure.i"
	@echo "... configure.s"
	@echo "... cuChromosome.o"
	@echo "... cuChromosome.i"
	@echo "... cuChromosome.s"
	@echo "... cuJob.o"
	@echo "... cuJob.i"
	@echo "... cuJob.s"
	@echo "... cuMachine.o"
	@echo "... cuMachine.i"
	@echo "... cuMachine.s"
	@echo "... cumain.o"
	@echo "... cumain.i"
	@echo "... cumain.s"
	@echo "... job_base.o"
	@echo "... job_base.i"
	@echo "... job_base.s"
	@echo "... unit_test.o"
	@echo "... unit_test.i"
	@echo "... unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

